import type { Metadata } from "next";
import "./globals.css";
import Footer from "./components/footer";
import Navigation from "./Navigation";
import MainLayout from "./components/layout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-black text-white">
        <Navigation />
        <MainLayout>{children}</MainLayout>
        <Footer />
      </body>
    </html>
  );
}
